apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox
spec:
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      containers:
      - image: prom/blackbox-exporter:v0.23.0
        name: blackbox
        ports:
        - containerPort: 9115
        volumeMounts:
        - name: config
          mountPath: /etc/blackbox_exporter
        args:
        - --config.file=/etc/blackbox_exporter/config.yml # Configmap 中的配置文件
        - --log.level=info  # 错误级别控制
        #- --log.level=error  # 错误级别控制
      volumes:
      - name: config
        configMap:
          name: blackbox
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-svc
spec:
  selector:
    app: blackbox
  ports:
  - port: 9115
    targetPort: 9115
  allocateLoadBalancerNodePorts: true
  sessionAffinity: None
  type: LoadBalancer

