{
 "title": "Decentralized Blackbox Exporter",
 "description": "Dashboard for decentralized Blackbox Exporters. Mostly for DNS and HTTP/HTTPS Tests",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "blackboxes",
    "label": "blackboxes",
    "query": {
     "query": "label_values(up,blackbox_instance)"
    }
   },
   {
    "name": "targets",
    "label": "targets",
    "query": {
     "query": "label_values(up{blackbox_instance=~\"$blackboxes\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,15s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "job_name",
    "query": {
     "query": "label_values(probe_dns_query_succeeded{},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP/HTTPS Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{blackbox_instance=~\"$blackboxes\",instance=~\"$targets\"}",
     "legendFormat": "{{blackbox_instance}}[{{job}}]"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{blackbox_instance=~\"$blackboxes\",instance=~\"$targets\"}",
     "legendFormat": "{{blackbox_instance}}[{{job}}]"
    }
   ]
  },
  {
   "title": "Average HTTP/HTTPS Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$targets\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$targets\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS 请求成功率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "100 * (sum_over_time(probe_dns_query_succeeded{}[$__interval]) /  count_over_time(probe_dns_query_succeeded{}[$__interval]) )",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}